Add node count status and CTA
kubeshark/front pull request #24
Opened 2023-08-28 03:09 UTC by manfioLP

Issue: https://github.com/orgs/kubeshark/projects/2/views/3?pane=issue&itemId=35616617

- Remove text from top bar
- Add upgrade button for cases where license is over node limit
- Change styling according to new design from @javier000icaic

2023-08-31 03:09 UTC, mertyildiran requested changes

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.sass
> +    font-family: Roboto, sans-serif
```suggestion
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.sass
> +    font-family: 'Source Sans Pro', sans-serif
```suggestion
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.sass
>    .edition
```suggestion
  .nodeLimit
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.tsx
> +      <div className="edition">
```suggestion
      <div className="nodeLimit">
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.sass
> +  .upgrade-button
```suggestion
  .upgradeButton
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.sass
> +  .text-upgrade-button
```suggestion
  .textUpgradeButton
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.tsx
> +              <Typography classes={{ root: 'text-upgrade-button' }}>
```suggestion
            <Button classes={{ root: 'upgradeButton' }} variant="outlined" size="small">
              <Typography classes={{ root: 'textUpgradeButton' }}>
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.tsx
> +          {upgrade && <ErrorIcon className="failure icon"/>}
```suggestion
          {upgrade && 
          <Tooltip title="Your node count isn't with-in your tier allowed limit. Either reduce the number of active nodes or obtain a license by pressing the upgrade button." arrow>
            <ErrorIcon className="failure icon"/>}
          </Tooltip>
```

2023-08-31 03:09 UTC, mertyildiran commented on src/components/Header/Header.tsx
> +import { Link, Button, Typography } from "@mui/material";
```suggestion
import { Link, Button, Typography, Tooltip } from "@mui/material";
```

2023-08-31 16:58 UTC, manfioLP commented on src/components/Header/Header.tsx
> +          {upgrade && <ErrorIcon className="failure icon"/>}
Implemented a different suggestion to match design, but I will mark resolved since it covers the Tooltip

2023-08-31 16:58 UTC, manfioLP commented on src/components/Header/Header.tsx
> +import { Link, Button, Typography } from "@mui/material";
I imported the Tooltip we already have on Project

2023-08-31 17:58 UTC, manfioLP commented on src/variables.module.scss
> +$failure-color: #DB2156;
didn't removed it, but actually reverted `failure-color` and then added a new color, `upgrade-color`

2023-09-01 00:29 UTC, mertyildiran approved these changes

2023-09-01 00:30 UTC, merged